### ISSUE TITLE
@vite/client added twice

### ISSUE THREAD

**Issue by werner-freytag** [swordfox/vite#1]
Hi! The `@vite/client` is added twice, in Vite.php:42 and Vite.php:44. I think one of them could be removed.

**Comment by goldfinch** [comment]
Hey,

Yeah, the client module loads twice, the same output has Laravel using Vite. Not entirely sure why. I assume that each asset could be included individually, and we probably need to make sure the vite client loads first. As far as I'm aware, it's not causing issues and only appears in dev mode. While in `build` both are replaced with relationship `preload` tags.

I moved the other one to CSS method, to avoid confusion.

Thanks for noticing that anyway.
